import enum
from datetime import datetime, timezone
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text, Enum
from sqlalchemy.orm import relationship
from app.core.database import Base


class CheckAction(str, enum.Enum):
    CHECK = "check"
    UNCHECK = "uncheck"
    UNLOAD = "unload"
    RECHECK = "recheck"


class ActorKind(str, enum.Enum):
    LOADER = "loader"
    DISPATCHER = "dispatcher"
    SYSTEM = "system"


class ReleaseAction(str, enum.Enum):
    RELEASE = "release"
    UNDO = "undo"


class LoadingCheck(Base):
    """Append-only record of every check, uncheck, unload and re-check.

    client_action_id is generated by the tablet, not the server, and is unique.
    The dock tablet queues actions in IndexedDB while offline and replays them on
    reconnect, so the same action can arrive more than once; the unique constraint
    is what makes those retries safe. Building it in now avoids retrofitting
    idempotency onto endpoints that already have callers.

    RunStopOrder.state holds the current value for cheap checklist reads; this
    table is the history behind it, and what the activity log is built from.
    """

    __tablename__ = "loading_checks"

    id = Column(Integer, primary_key=True, index=True)
    run_stop_order_id = Column(Integer, ForeignKey("run_stop_orders.id"), nullable=False)
    action = Column(Enum(CheckAction), nullable=False)
    actor_id = Column(Integer, ForeignKey("loader_users.id"), nullable=True)
    at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    client_action_id = Column(String(64), unique=True, index=True, nullable=True)
    plan_version = Column(Integer, nullable=True)

    run_stop_order = relationship("RunStopOrder")
    actor = relationship("LoaderUser")


class RunReleaseAction(Base):
    """Append-only record of a run being released or the release being undone.

    A table rather than a column on delivery_runs, because release is the one
    write that REPEATS on the same row: mark ready -> undo within 10 s -> mark
    ready again is a normal sequence. A single delivery_runs.client_action_id
    would be overwritten each time, so the first release's id would be forgotten
    and its offline replay would be applied a second time. It also could not tell
    a replayed release from a replayed undo.

    Same shape and the same reasoning as LoadingCheck, which is append-only for
    exactly the same reason - checks repeat too.
    """

    __tablename__ = "run_release_actions"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(Integer, ForeignKey("delivery_runs.id"), nullable=False)
    action = Column(Enum(ReleaseAction), nullable=False)
    actor_id = Column(Integer, ForeignKey("loader_users.id"), nullable=True)
    at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    client_action_id = Column(String(64), unique=True, index=True, nullable=True)

    run = relationship("DeliveryRun")
    actor = relationship("LoaderUser")


class LoaderActivity(Base):
    """Timeline of what happened on a run.

    Feeds both the loader's Log tab and the Change log panel on the checklist
    ("02:14 Dispatcher published plan v3 / 02:16 Acknowledged - Saman J."), and is
    the same feed the dispatcher reads on their Delivery Runs view.

    actor_kind distinguishes the three sources the timeline mixes: the loader, the
    dispatcher, and the system itself (for example applying an escalation default
    when a decide-by time passes).
    """

    __tablename__ = "loader_activities"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(Integer, ForeignKey("delivery_runs.id"), nullable=False)
    at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    actor_kind = Column(Enum(ActorKind), nullable=False)
    actor_id = Column(Integer, ForeignKey("loader_users.id"), nullable=True)
    actor_label = Column(String(255), nullable=True)
    event_type = Column(String(100), nullable=False)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=True)
    message = Column(Text, nullable=False)

    run = relationship("DeliveryRun")
    actor = relationship("LoaderUser")
    order = relationship("Order")
