"""loader foundation

Sits on top of the dev chain (0001_baseline -> bbb8d4327f93 -> 552931e83b93 ->
af60e6fa37a0 -> 0a80c3e0353c -> c9228f7f0a72 -> 50ff454ecd63), so it only creates
what the shared database does not already have:

- No `vehicles` table: that is Thisaru's (bbb8d4327f93, app.models.fleet.Vehicle).
  delivery_runs.vehicle_id points at it. The loader reads temperature_mode and
  depot_name for what it used to call temp_capability and depot, so no columns
  are added to it.
- The loader issue enums are named loaderissuetype / loaderissuestatus, because
  the driver team's issue_reports (50ff454ecd63) already created the Postgres
  types issuetype and issuestatus.

Revision ID: 0002_loader_foundation
Revises: 50ff454ecd63
Create Date: 2026-09-29 16:33:37.028402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_loader_foundation'
down_revision: Union[str, Sequence[str], None] = '50ff454ecd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_operating', sa.Boolean(), nullable=False),
    sa.Column('festival_ramp', sa.Float(), nullable=False),
    sa.Column('monsoon', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_calendar_days_date'), 'calendar_days', ['date'], unique=False)
    op.create_table('docks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('depot', sa.Enum('PELIYAGODA', 'KANDY', name='depot'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docks_code'), 'docks', ['code'], unique=True)
    op.create_index(op.f('ix_docks_id'), 'docks', ['id'], unique=False)
    op.create_table('outlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.Enum('FRESH', 'STYLE', 'TECH', name='brand'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('dock_type', sa.Enum('REAR_DOCK', 'STREET', 'MALL_BAY', name='docktype'), nullable=False),
    sa.Column('van_only', sa.Boolean(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=True),
    sa.Column('window_end', sa.Time(), nullable=True),
    sa.Column('depot', sa.Enum('PELIYAGODA', 'KANDY', name='depot'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlets_code'), 'outlets', ['code'], unique=True)
    op.create_index(op.f('ix_outlets_id'), 'outlets', ['id'], unique=False)
    op.create_table('dock_tablets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('dock_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_dock_tablets_id'), 'dock_tablets', ['id'], unique=False)
    op.create_index(op.f('ix_dock_tablets_label'), 'dock_tablets', ['label'], unique=True)
    op.create_table('loader_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('home_dock_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_dock_id'], ['docks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loader_users_id'), 'loader_users', ['id'], unique=False)
    op.create_table('delivery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('dock_id', sa.Integer(), nullable=False),
    sa.Column('trip_number', sa.Integer(), nullable=False),
    sa.Column('brand', sa.Enum('FRESH', 'STYLE', 'TECH', name='brand'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('wave', sa.String(length=50), nullable=True),
    sa.Column('departs_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'LOADING', 'ISSUE_FLAGGED', 'LOADED', 'READY_TO_DEPART', 'GATED_OUT', name='runstatus'), nullable=False),
    sa.Column('current_plan_version', sa.Integer(), nullable=False),
    sa.Column('planned_weight_kg', sa.Float(), nullable=False),
    sa.Column('planned_volume_m3', sa.Float(), nullable=False),
    sa.Column('loaded_weight_kg', sa.Float(), nullable=False),
    sa.Column('loaded_volume_m3', sa.Float(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('gated_out_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_trip_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_trip_id'], ['dispatch_trips.id'], ),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], ),
    sa.ForeignKeyConstraint(['released_by_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_runs_code'), 'delivery_runs', ['code'], unique=True)
    op.create_index(op.f('ix_delivery_runs_id'), 'delivery_runs', ['id'], unique=False)
    op.create_table('loader_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loader_user_id', sa.Integer(), nullable=False),
    sa.Column('dock_tablet_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.Enum('IDLE_TIMEOUT', 'SWITCH_USER', 'SIGN_OUT', name='sessionendreason'), nullable=True),
    sa.ForeignKeyConstraint(['dock_tablet_id'], ['dock_tablets.id'], ),
    sa.ForeignKeyConstraint(['loader_user_id'], ['loader_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loader_sessions_id'), 'loader_sessions', ['id'], unique=False)
    op.create_table('loader_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_kind', sa.Enum('LOADER', 'DISPATCHER', 'SYSTEM', name='actorkind'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['delivery_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loader_activities_at'), 'loader_activities', ['at'], unique=False)
    op.create_index(op.f('ix_loader_activities_id'), 'loader_activities', ['id'], unique=False)
    op.create_table('loader_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('MISSING', 'SHORT', 'DAMAGED', 'WONT_FIT', name='loaderissuetype'), nullable=False),
    sa.Column('units_affected', sa.Integer(), nullable=True),
    sa.Column('units_total', sa.Integer(), nullable=True),
    sa.Column('quick_note_tag', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'SEEN', 'DECIDED', 'DEFAULT_APPLIED', name='loaderissuestatus'), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('decide_by', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('client_action_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['delivery_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loader_issues_client_action_id'), 'loader_issues', ['client_action_id'], unique=True)
    op.create_index(op.f('ix_loader_issues_id'), 'loader_issues', ['id'], unique=False)
    op.create_table('plan_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('planned_weight_kg', sa.Float(), nullable=True),
    sa.Column('planned_volume_m3', sa.Float(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('client_action_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['delivery_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'version', name='uq_plan_revision_version')
    )
    op.create_index(op.f('ix_plan_revisions_client_action_id'), 'plan_revisions', ['client_action_id'], unique=True)
    op.create_index(op.f('ix_plan_revisions_id'), 'plan_revisions', ['id'], unique=False)
    op.create_table('run_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('load_position', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('handling_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'LOADING', 'COMPLETE', name='stopstatus'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['delivery_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'plan_version', 'stop_sequence', name='uq_run_stop_sequence')
    )
    op.create_index(op.f('ix_run_stops_id'), 'run_stops', ['id'], unique=False)
    op.create_table('loader_issue_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_chosen', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['loader_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loader_issue_options_id'), 'loader_issue_options', ['id'], unique=False)
    op.create_table('plan_revision_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('change_kind', sa.Enum('UNLOAD_FROM_TRUCK', 'DONT_LOAD', 'LOAD_NEW', 'RESEQUENCE', name='planchangekind'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['plan_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_revision_changes_id'), 'plan_revision_changes', ['id'], unique=False)
    op.create_table('run_stop_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_stop_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('TO_LOAD', 'LOADED', 'FLAGGED', 'RE_CHECK', 'TAKE_OFF', 'MOVED', 'NEW', name='runorderstate'), nullable=False),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('checked_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['run_stop_id'], ['run_stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_stop_id', 'order_id', name='uq_run_stop_order')
    )
    op.create_index(op.f('ix_run_stop_orders_id'), 'run_stop_orders', ['id'], unique=False)
    op.create_table('loading_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_stop_order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CHECK', 'UNCHECK', 'UNLOAD', 'RECHECK', name='checkaction'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('client_action_id', sa.String(length=64), nullable=True),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['run_stop_order_id'], ['run_stop_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loading_checks_client_action_id'), 'loading_checks', ['client_action_id'], unique=True)
    op.create_index(op.f('ix_loading_checks_id'), 'loading_checks', ['id'], unique=False)
    op.create_table('run_release_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('RELEASE', 'UNDO', name='releaseaction'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('client_action_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['loader_users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['delivery_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_release_actions_client_action_id'), 'run_release_actions', ['client_action_id'], unique=True)
    op.create_index(op.f('ix_run_release_actions_id'), 'run_release_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_release_actions_id'), table_name='run_release_actions')
    op.drop_index(op.f('ix_run_release_actions_client_action_id'), table_name='run_release_actions')
    op.drop_table('run_release_actions')
    op.drop_index(op.f('ix_loading_checks_id'), table_name='loading_checks')
    op.drop_index(op.f('ix_loading_checks_client_action_id'), table_name='loading_checks')
    op.drop_table('loading_checks')
    op.drop_index(op.f('ix_run_stop_orders_id'), table_name='run_stop_orders')
    op.drop_table('run_stop_orders')
    op.drop_index(op.f('ix_plan_revision_changes_id'), table_name='plan_revision_changes')
    op.drop_table('plan_revision_changes')
    op.drop_index(op.f('ix_loader_issue_options_id'), table_name='loader_issue_options')
    op.drop_table('loader_issue_options')
    op.drop_index(op.f('ix_run_stops_id'), table_name='run_stops')
    op.drop_table('run_stops')
    op.drop_index(op.f('ix_plan_revisions_client_action_id'), table_name='plan_revisions')
    op.drop_index(op.f('ix_plan_revisions_id'), table_name='plan_revisions')
    op.drop_table('plan_revisions')
    op.drop_index(op.f('ix_loader_issues_client_action_id'), table_name='loader_issues')
    op.drop_index(op.f('ix_loader_issues_id'), table_name='loader_issues')
    op.drop_table('loader_issues')
    op.drop_index(op.f('ix_loader_activities_id'), table_name='loader_activities')
    op.drop_index(op.f('ix_loader_activities_at'), table_name='loader_activities')
    op.drop_table('loader_activities')
    op.drop_index(op.f('ix_loader_sessions_id'), table_name='loader_sessions')
    op.drop_table('loader_sessions')
    op.drop_index(op.f('ix_delivery_runs_id'), table_name='delivery_runs')
    op.drop_index(op.f('ix_delivery_runs_code'), table_name='delivery_runs')
    op.drop_table('delivery_runs')
    op.drop_index(op.f('ix_loader_users_id'), table_name='loader_users')
    op.drop_table('loader_users')
    op.drop_index(op.f('ix_dock_tablets_label'), table_name='dock_tablets')
    op.drop_index(op.f('ix_dock_tablets_id'), table_name='dock_tablets')
    op.drop_table('dock_tablets')
    op.drop_index(op.f('ix_outlets_id'), table_name='outlets')
    op.drop_index(op.f('ix_outlets_code'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_index(op.f('ix_docks_id'), table_name='docks')
    op.drop_index(op.f('ix_docks_code'), table_name='docks')
    op.drop_table('docks')
    op.drop_index(op.f('ix_calendar_days_date'), table_name='calendar_days')
    op.drop_table('calendar_days')
    # ### end Alembic commands ###

    # Same trap as 0001: create_table() creates these named ENUM types implicitly,
    # but autogenerate does not drop them, so a second upgrade would fail with
    # "type <name> already exists". Postgres only.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "actorkind",
            "releaseaction",
            "checkaction",
            "loaderissuestatus",
            "loaderissuetype",
            "planchangekind",
            "runorderstate",
            "runstatus",
            "stopstatus",
            "sessionendreason",
            "docktype",
            "brand",
            "depot",
        ):
            op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
