"""driver_tables

Revision ID: 50ff454ecd63
Revises: a7802bcab197
Create Date: 2026-09-30 10:56:33.216421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ff454ecd63'
down_revision: Union[str, Sequence[str], None] = 'c9228f7f0a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_trip_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'STARTED', 'COMPLETED', name='drivertripstatus'), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_trip_id'], ['dispatch_trips.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_trips_id'), 'driver_trips', ['id'], unique=False)
    op.create_table('delivery_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_trip_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ARRIVED', 'DELIVERED', 'FAILED', 'PARTIAL', 'RESCHEDULED', name='deliverystopstatus'), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_trip_id'], ['driver_trips.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_stops_id'), 'delivery_stops', ['id'], unique=False)
    op.create_table('sos_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_trip_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('TRIGGERED', 'ACKNOWLEDGED', 'RESOLVED', name='sosstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_trip_id'], ['driver_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_alerts_id'), 'sos_alerts', ['id'], unique=False)
    op.create_table('issue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('driver_trip_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('VEHICLE_BREAKDOWN', 'TRAFFIC_DELAY', 'CUSTOMER_UNAVAILABLE', 'DAMAGED_GOODS', 'WRONG_ADDRESS', 'OTHER', name='issuetype'), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='issuestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_trip_id'], ['driver_trips.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['delivery_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_reports_id'), 'issue_reports', ['id'], unique=False)
    op.create_table('proof_of_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['delivery_stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stop_id')
    )
    op.create_index(op.f('ix_proof_of_delivery_id'), 'proof_of_delivery', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_proof_of_delivery_id'), table_name='proof_of_delivery')
    op.drop_table('proof_of_delivery')
    op.drop_index(op.f('ix_issue_reports_id'), table_name='issue_reports')
    op.drop_table('issue_reports')
    op.drop_index(op.f('ix_sos_alerts_id'), table_name='sos_alerts')
    op.drop_table('sos_alerts')
    op.drop_index(op.f('ix_delivery_stops_id'), table_name='delivery_stops')
    op.drop_table('delivery_stops')
    op.drop_index(op.f('ix_driver_trips_id'), table_name='driver_trips')
    op.drop_table('driver_trips')
    # ### end Alembic commands ###
