"""Add enterprise fields to vehicle and allocation

Revision ID: 552931e83b93
Revises: bbb8d4327f93
Create Date: 2026-09-29 20:03:36.842855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552931e83b93'
down_revision: Union[str, Sequence[str], None] = 'bbb8d4327f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('volume_percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('vehicles', sa.Column('temperature_mode', sa.String(length=50), nullable=False, server_default='Ambient'))
    op.add_column('vehicles', sa.Column('depot_name', sa.String(length=100), nullable=False, server_default='Central Depot'))
    op.add_column('vehicles', sa.Column('weekly_fuel_status', sa.String(length=50), nullable=False, server_default='Ambient'))
    op.add_column('vehicles', sa.Column('trips_today', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vehicles', sa.Column('trips_planned', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vehicles', sa.Column('maintenance_state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'maintenance_state')
    op.drop_column('vehicles', 'trips_planned')
    op.drop_column('vehicles', 'trips_today')
    op.drop_column('vehicles', 'weekly_fuel_status')
    op.drop_column('vehicles', 'depot_name')
    op.drop_column('vehicles', 'temperature_mode')
    op.drop_column('allocations', 'volume_percentage')
    # ### end Alembic commands ###
