"""added allocations

Revision ID: bbb8d4327f93
Revises: 
Create Date: 2026-09-29 17:23:44.869477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb8d4327f93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('capacity_vol_m3', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ALLOCATED', 'LOADING', 'UNAVAILABLE', name='vehiclestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_code'), 'vehicles', ['code'], unique=True)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('driver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_driver_profiles_id'), 'driver_profiles', ['id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('load_percentage', sa.Float(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ALLOCATED', 'READY', 'LOADING', 'DISPATCHED', 'COMPLETED', 'CANCELLED', name='allocationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_index(op.f('ix_allocations_run_id'), 'allocations', ['run_id'], unique=False)
    op.add_column('orders', sa.Column('allocation_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_allocation_id', 'orders', 'allocations', ['allocation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_allocation_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'allocation_id')
    op.drop_index(op.f('ix_allocations_run_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_driver_profiles_id'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_code'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
